// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: awesomedata.proto

#ifndef PROTOBUF_INCLUDED_awesomedata_2eproto
#define PROTOBUF_INCLUDED_awesomedata_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_awesomedata_2eproto 

namespace protobuf_awesomedata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_awesomedata_2eproto
namespace protobuf {
class AwesomeData;
class AwesomeDataDefaultTypeInternal;
extern AwesomeDataDefaultTypeInternal _AwesomeData_default_instance_;
}  // namespace protobuf
namespace google {
namespace protobuf {
template<> ::protobuf::AwesomeData* Arena::CreateMaybeMessage<::protobuf::AwesomeData>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protobuf {

// ===================================================================

class AwesomeData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protobuf.AwesomeData) */ {
 public:
  AwesomeData();
  virtual ~AwesomeData();

  AwesomeData(const AwesomeData& from);

  inline AwesomeData& operator=(const AwesomeData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AwesomeData(AwesomeData&& from) noexcept
    : AwesomeData() {
    *this = ::std::move(from);
  }

  inline AwesomeData& operator=(AwesomeData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AwesomeData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AwesomeData* internal_default_instance() {
    return reinterpret_cast<const AwesomeData*>(
               &_AwesomeData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AwesomeData* other);
  friend void swap(AwesomeData& a, AwesomeData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AwesomeData* New() const final {
    return CreateMaybeMessage<AwesomeData>(NULL);
  }

  AwesomeData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AwesomeData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AwesomeData& from);
  void MergeFrom(const AwesomeData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AwesomeData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated float somearray = 2;
  int somearray_size() const;
  void clear_somearray();
  static const int kSomearrayFieldNumber = 2;
  float somearray(int index) const;
  void set_somearray(int index, float value);
  void add_somearray(float value);
  const ::google::protobuf::RepeatedField< float >&
      somearray() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_somearray();

  // string somestring = 1;
  void clear_somestring();
  static const int kSomestringFieldNumber = 1;
  const ::std::string& somestring() const;
  void set_somestring(const ::std::string& value);
  #if LANG_CXX11
  void set_somestring(::std::string&& value);
  #endif
  void set_somestring(const char* value);
  void set_somestring(const char* value, size_t size);
  ::std::string* mutable_somestring();
  ::std::string* release_somestring();
  void set_allocated_somestring(::std::string* somestring);

  // @@protoc_insertion_point(class_scope:protobuf.AwesomeData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< float > somearray_;
  mutable int _somearray_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr somestring_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_awesomedata_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AwesomeData

// string somestring = 1;
inline void AwesomeData::clear_somestring() {
  somestring_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AwesomeData::somestring() const {
  // @@protoc_insertion_point(field_get:protobuf.AwesomeData.somestring)
  return somestring_.GetNoArena();
}
inline void AwesomeData::set_somestring(const ::std::string& value) {
  
  somestring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protobuf.AwesomeData.somestring)
}
#if LANG_CXX11
inline void AwesomeData::set_somestring(::std::string&& value) {
  
  somestring_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protobuf.AwesomeData.somestring)
}
#endif
inline void AwesomeData::set_somestring(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  somestring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protobuf.AwesomeData.somestring)
}
inline void AwesomeData::set_somestring(const char* value, size_t size) {
  
  somestring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protobuf.AwesomeData.somestring)
}
inline ::std::string* AwesomeData::mutable_somestring() {
  
  // @@protoc_insertion_point(field_mutable:protobuf.AwesomeData.somestring)
  return somestring_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AwesomeData::release_somestring() {
  // @@protoc_insertion_point(field_release:protobuf.AwesomeData.somestring)
  
  return somestring_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AwesomeData::set_allocated_somestring(::std::string* somestring) {
  if (somestring != NULL) {
    
  } else {
    
  }
  somestring_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), somestring);
  // @@protoc_insertion_point(field_set_allocated:protobuf.AwesomeData.somestring)
}

// repeated float somearray = 2;
inline int AwesomeData::somearray_size() const {
  return somearray_.size();
}
inline void AwesomeData::clear_somearray() {
  somearray_.Clear();
}
inline float AwesomeData::somearray(int index) const {
  // @@protoc_insertion_point(field_get:protobuf.AwesomeData.somearray)
  return somearray_.Get(index);
}
inline void AwesomeData::set_somearray(int index, float value) {
  somearray_.Set(index, value);
  // @@protoc_insertion_point(field_set:protobuf.AwesomeData.somearray)
}
inline void AwesomeData::add_somearray(float value) {
  somearray_.Add(value);
  // @@protoc_insertion_point(field_add:protobuf.AwesomeData.somearray)
}
inline const ::google::protobuf::RepeatedField< float >&
AwesomeData::somearray() const {
  // @@protoc_insertion_point(field_list:protobuf.AwesomeData.somearray)
  return somearray_;
}
inline ::google::protobuf::RepeatedField< float >*
AwesomeData::mutable_somearray() {
  // @@protoc_insertion_point(field_mutable_list:protobuf.AwesomeData.somearray)
  return &somearray_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_awesomedata_2eproto
